version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/filehosting
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
    restart: always
    links:
      - php
      - postgres
      - redis
      - sphinx
  php:
    container_name: php
    build:
      context: .docker/php
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/filehosting
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    restart: always
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: filehosting_production
      POSTGRES_USER: filehosting
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5432:5432"
    restart: always
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
  sphinx:
    container_name: sphinx
    image: macbre/sphinxsearch:latest
    volumes:
      - ./config/sphinx.conf:/opt/sphinx/conf/sphinx.conf
    ports:
      - "9306:9306"
    restart: always