version: '3'

services:
  web:
    container_name: filehosting.site
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/filehosting
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
    restart: always
    depends_on:
      - php
      - postgres
      - redis
      - sphinx
  php:
    container_name: php
    build:
      context: .docker/php
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/filehosting
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    restart: always
    privileged: true
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: filehosting_testing
      POSTGRES_USER: filehosting
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5432:5432"
    restart: always
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
  sphinx:
    container_name: sphinx
    image: macbre/sphinxsearch:latest
    volumes:
      - ./tests/_data/sphinxsearch/data:/opt/sphinx/index
      - ./config/sphinx_testing.conf:/opt/sphinx/conf/sphinx.conf
    ports:
      - "9306:9306"
    restart: always
  codecept:
    container_name: codeception
    build:
      context: .docker/codecept
      dockerfile: Dockerfile
    volumes:
      - .:/project
      - ./tests:/project/tests
      - ./codeception.yml:/project/codeception.yml
    depends_on:
      - web
      - chrome
  chrome:
    container_name: chrome
    image: selenium/standalone-chrome-debug:3.13
    ports:
      - "4444"
      - "5900"